CREATE INDEX `connections_requester_id_idx` ON `connections` (`requester_id`);--> statement-breakpoint
CREATE INDEX `connections_recipient_id_idx` ON `connections` (`recipient_id`);--> statement-breakpoint
CREATE INDEX `connections_status_idx` ON `connections` (`status`);--> statement-breakpoint
CREATE INDEX `connections_requester_recipient_idx` ON `connections` (`requester_id`,`recipient_id`);--> statement-breakpoint
CREATE INDEX `entrepreneur_profiles_profile_id_idx` ON `entrepreneur_profiles` (`profile_id`);--> statement-breakpoint
CREATE INDEX `entrepreneur_profiles_industry_idx` ON `entrepreneur_profiles` (`industry`);--> statement-breakpoint
CREATE INDEX `entrepreneur_profiles_funding_stage_idx` ON `entrepreneur_profiles` (`funding_stage`);--> statement-breakpoint
CREATE INDEX `entrepreneur_profiles_location_idx` ON `entrepreneur_profiles` (`location`);--> statement-breakpoint
CREATE INDEX `favorites_profile_id_idx` ON `favorites` (`profile_id`);--> statement-breakpoint
CREATE INDEX `favorites_favorited_profile_id_idx` ON `favorites` (`favorited_profile_id`);--> statement-breakpoint
CREATE INDEX `favorites_profile_favorited_idx` ON `favorites` (`profile_id`,`favorited_profile_id`);--> statement-breakpoint
CREATE INDEX `investor_profiles_profile_id_idx` ON `investor_profiles` (`profile_id`);--> statement-breakpoint
CREATE INDEX `investor_profiles_industry_focus_idx` ON `investor_profiles` (`industry_focus`);--> statement-breakpoint
CREATE INDEX `investor_profiles_location_idx` ON `investor_profiles` (`location`);--> statement-breakpoint
CREATE INDEX `messages_connection_id_idx` ON `messages` (`connection_id`);--> statement-breakpoint
CREATE INDEX `messages_created_at_idx` ON `messages` (`created_at`);--> statement-breakpoint
CREATE INDEX `messages_connection_created_idx` ON `messages` (`connection_id`,`created_at`);--> statement-breakpoint
CREATE INDEX `notifications_profile_id_idx` ON `notifications` (`profile_id`);--> statement-breakpoint
CREATE INDEX `notifications_is_read_idx` ON `notifications` (`is_read`);--> statement-breakpoint
CREATE INDEX `notifications_created_at_idx` ON `notifications` (`created_at`);--> statement-breakpoint
CREATE INDEX `notifications_profile_read_idx` ON `notifications` (`profile_id`,`is_read`);--> statement-breakpoint
CREATE INDEX `profile_views_viewed_profile_id_idx` ON `profile_views` (`viewed_profile_id`);--> statement-breakpoint
CREATE INDEX `profile_views_created_at_idx` ON `profile_views` (`created_at`);--> statement-breakpoint
CREATE INDEX `profiles_user_id_idx` ON `profiles` (`user_id`);--> statement-breakpoint
CREATE INDEX `profiles_role_idx` ON `profiles` (`role`);--> statement-breakpoint
CREATE INDEX `video_views_video_id_idx` ON `video_views` (`video_id`);--> statement-breakpoint
CREATE INDEX `videos_profile_id_idx` ON `videos` (`profile_id`);--> statement-breakpoint
CREATE INDEX `videos_created_at_idx` ON `videos` (`created_at`);--> statement-breakpoint
CREATE INDEX `videos_views_count_idx` ON `videos` (`views_count`);